<?php

function ajax_reader_menu() {
    $items['ajax-r'] = array(
        'title' => 'Ajax Start Page',
        'page callback' => 'ajax_start_page',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['ajax-reader'] = array(
        'title' => 'Ajax Reader Page',
        'page callback' => 'ajax_reader_page',
        'access callback' => 'user_access',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function ajax_reader_page($type = 'ajax', $nid = 0) {
    $output = _ajax_reader_load_noder($nid);
    if($type == 'ajax') {
        $commands[] = ajax_command_replace('#content', '<div id="content">' . $output . '</div>');
        $page = array(
            '#type' => 'ajax',
            '#commands' => $commands
        );
        ajax_deliver($page);
    }
    elseif ($nid > 0) {
        drupal_goto('node/' . $nid);
    }
    else {
        $output = '<div id="content">' . $output . '</div>';
        return $output;
    }
}

function _ajax_reader_load_noder($nid = 0) {
    $node = node_load($nid, NULL, false);
    if($node) {
        $vnode = node_view($node);
        return theme("node", $vnode);
    }
    //return views_embed_view('front', 'page_1', $nid);
}

function ajax_start_page() {
    return '<a href="/ajax-reader/nojs/2" class="use-ajax">Click This</a>';
}
